eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8881
spring:
  application:
    name: CONFIG-CLIENT
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: CONFIG-SERVER